version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/ts"
      - "/spec"
    schedule:
      interval: daily
      day: sunday
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
        update-types: [minor, patch]
      prod-minor-patch:
        dependency-type: production
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directories:
      - "/.github/workflows"
    schedule:
      interval: daily
      day: sunday
    group:
      actions:
        patterns: ["*"]

